nodeLinker: node-modules

npmScopes:
  agv:
    npmAlwaysAuth: true
    npmAuthToken: "${CODEARTIFACT_AUTH_TOKEN}"
    npmRegistryServer: "https://agv-293859034925.d.codeartifact.eu-central-1.amazonaws.com/npm/agv-node/"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
