# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
      - "react-timeseries-charts/*"
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"
      - name: Obtain AWS Token for CodeArtifact
        run: echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ secrets.CA_DOMAIN }} --domain-owner ${{ secrets.CA_DOMAIN_OWNER }} --query authorizationToken --output text --duration-seconds 900)" >> $GITHUB_ENV
      - name: Mask token from logs
        run: echo "::add-mask::$CODEARTIFACT_AUTH_TOKEN"
      - name: Setup yarn
        run: yarn set version 3.1.1
      - run: yarn
      - run: yarn build
      - run: yarn npm publish